name: build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12, 14, 16]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

